### ISSUE TITLE
issues with ListItemIcon (material-ui library)

### ISSUE THREAD

**Issue by diogoweb2** [TroyAlford/react-jsx-parser#24] opened 2017-07-26 17:21 UTC
First, nice project. 

It worked fine util I added ListItemIcon:
 `<JsxParser
          components={{ List, ListItem, ListItemIcon, ListItemText, InboxIcon }}
          jsx={
            '<ListItem button><ListItemIcon> <InboxIcon /></ListItemIcon><ListItemText primary="Dashboard" /> </ListItem>       '
          }
        />`

Error: 
Uncaught TypeError: Cannot read property 'className' of undefined
    at ListItemIcon (ListItemIcon.js:58)
    at createEagerElementUtil (createEagerElementUtil.js:18)
    at createEagerFactory.js:18
    at Style.render (withStyles.js:324)
    at ReactCompositeComponent.js:795
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:794)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:821)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:361)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:257)

--------

Library:
https://material-ui-1dab0.firebaseapp.com/

**Comment by TroyAlford** [comment] 2017-07-26 18:52
@diogoweb2 - thanks for the kind words!

https://github.com/callemall/material-ui/blob/v1-beta/src/List/ListItemIcon.js appears to be the source for the file in question (`ListItemIcon.js`) - though I'm guessing line 58 is referring to the transpiled version. My suspicion is that something about the transpilation assumes that the `className` prop is non-null - while your actual JSX does not set it.

I can't be sure without an actual repro, though. Would this be something you could reproduce in a Codepen or similar?

**Comment by diogoweb2** [comment] 2017-07-26 20:12
hi @TroyAlford , 
You can take a look on it here: (search for "JsxParser") 
https://www.webpackbin.com/bins/-Kq-MBvjM6FaQq3cKZd8

Thanks!

**Comment by TroyAlford** [comment] 2017-07-27 00:47
When I inspect the actual lines that are breaking, they're these - inside of the `ListItemIcon` element's transpiled function. In specific, this appears to be an issue with the assertion of `children.props.className` - which makes sense, since `children` should be a set, not an individual item which has props.

```es6
  return _react2.default.cloneElement(children, (0, _extends3.default)({
    className: (0, _classnames2.default)(classes.root, classNameProp, children.props.className)
  }, other));
```

In other words - I think you may want to submit a pull request to `material-ui`!

For reference - the broken line of code appears to be: 
https://github.com/callemall/material-ui/blob/v1-beta/src/List/ListItemIcon.js#L41

**Comment by TroyAlford** [comment] 2017-07-27 00:48
I'm going to close this issue, as I believe the problem to be in the other lib. Please feel free to re-open if you discover otherwise!

**Closed by TroyAlford** 2017-07-27 00:48 UTC
