### ISSUE TITLE
Higher order component for caching jsx?

### ISSUE THREAD

**Issue by mikeaustin** [TroyAlford/react-jsx-parser#99] opened 2019-07-17 21:21 UTC
This project looks awesome, and is nice and focused. My question is, if I render the component very often (drawing app, game, etc.) does it parse the JSX each time? It looks like it does.

```
  render = () => {
    const jsx = (this.props.jsx || '').trim().replace(/<!DOCTYPE([^>]*)>/g, '')
    this.ParsedChildren = this.parseJSX(jsx)
```

A higher-order-component could do the parsing, then return a regular component that can take props. I'm also looking into a template literal approach, which is another way to parse dynamic JSX. (https://medium.com/the-guild/implementing-a-runtime-version-of-jsx-78e004bf432e).

**Comment by TroyAlford** [comment] 2019-07-18 21:19
@mikeaustin - that's exactly right: the JSX will get re-parsed again and again, on every render. And yeah - a higher-order caching system of some kind might be pretty great. In most renders, the actual JSX is unlikely to change. Even a simple memoization would probably improve overall performance and memory footprint.

I'd be totally happy to collaborate on a PR for this, if you're interested.

**Comment by mikeaustin** [comment] 2019-07-30 05:45
For fun, I'm working on a vector drawing app (ala Sketch/Framer X) and it's been fun. One thing I was experimenting with was optimizing moving shapes. I kept a local translate state, and offset shape while dragging, then set the actual position on release. That ensures React won't update the entire shape tree, but it still has to set props on the shape itself, which will cause a render.

What are your thoughts for making a higher order component? Store the results of parse() with updatable content using refs or something similar?

**Comment by petertenhoor** [comment] 2019-08-09 19:41
I currently use moize.react (https://www.npmjs.com/package/moize#moizereact) around JsxParser to make sure that the same JSX string does not get parsed over and over again. Would that be a solution?

**Comment by TroyAlford** [comment] 2019-08-10 02:42
Hmm. I suspect that React's virtual DOM will obviate much of the work for us, if we can keep the keys the same between renders of the children. The issue is that as the JSX text changes, anything _after_ the change is no longer in the same position - and it is non-trivial to figure out what to do about that.

I think part of the issue, currently, is that the existing code does not create consistent `key` props for the children as it parses. `React` will do this on its own, of course, but we should really implement a similar mechanism.

Consider the following structure:
```
root
--> childA
  --> grandchildA1
  --> grandchildA2
--> childB
  --> grandchildB2
```

This should result in keys: A, A1, A2, B, and B2 - and potentially, we should actually add these keys in some fashion to the JSX itself. When a text edit occurs, however, we need to be able to figure out which `key` element that change actually matches up with - and ensure that the newly edited node maintains the key.

If the keys are generated as above, as a programmatic, unique indication of the tree structure, much of this happens "for free" - but there are odd edge-conditions, such as the insertion of a NEW node in-between two existing nodes. A node inserted between B1 and B2 would actually cause the existing B2 to become B3, and insert a new B2. Avoiding that is the problem.

It almost feels like we need some way to diff one JSX document with the next and apply only the changes. This is duplicative of what React itself already does - but the fact that JsxParser isn't already matching that is essentially why we have an issue.

Now all of that said - if all we want is a bit better performance, we could certainly just cache the parsing - specifically of opening tags with their props. There is a bit more complexity around handling the children as we create the elements, but caching the parsing of the opening tags, themselves, still gives us a benefit in performance, at the potential cost of memory size.

An LRU cache of some kind, maybe? And we could add a `prop` which indicates how many entries that cache can have, and defaults to something high?

**Comment by mikeaustin** [comment] 2019-08-11 01:00
Sorry for dining and dashing.. got some free time now. For context, I'm working on a vector drawing app just for fun: https://mike-austin.com/draw. Currently the ellipse is being rendered by JsxParser–it's rendering, but the events aren't getting passed through. I'm using react-native-web, but I don't think that should have any effect. You can see the source here: https://github.com/mikeaustin/grid-draw/blob/master/src/app/components/shapeRegistration.js.

**Comment by TroyAlford** [comment] 2019-09-07 16:15
Closing this issue due to lack of further activity.

**Closed as completed by TroyAlford** 2019-09-07 16:15 UTC
Labels: enhancement, help wanted
