### ISSUE TITLE
script tag not being blacklisted in 1.2.4

### ISSUE THREAD

**Issue by vatsalvora** [TroyAlford/react-jsx-parser#42] opened 2018-02-15 20:05 UTC
```javascript
<script>
</script>
<div>
       <ReactComponent />
</div>
```
or
```javascript
<script>
</script>
<div>
       <h1>Header</h1>
</div>
```
If I have a script tag in my html, then the React component or any other content does not get rendered.
Possibly the script tag is not being blacklisted.

My default props:
```
JsxParser.defaultProps = {
    bindings: {}, // by default, do not add any additional bindings

    // by default, just removes `on*` attributes (onClick, onChange, etc.)
    // values are used as a regex to match property names
    blacklistedAttrs: ['moduleTitle','elementId'], //= /on[a-z]*/gi

    // by default, removes all <script> tags
    blacklistedTags:  ['script'],

    //log errors
    onError: (error) => {console.log("Error by JSX Parser: ", error)},
    showWarnings: true,
    // Components must extend React.Component, React.PureComponent, or be a Function
    components: {},

    jsx: '',
};
```

**Comment by TroyAlford** [comment] 2018-02-16 06:59
Hi @vatsalvora - I just ran through the tests - and even ran your exact use-case - but I can't reproduce. In case I'm missing something, here is what I'm interpreting your use-case to be:

```javascript
render = () => (
  <JsxParser 
    jsx="<script></script><div><ReactComponent /></div>"
  />
)
```
If you are relying on the default bindings, above, this will strip the script tag correctly - but NOT your component, and you'll wind up rendering something similar to:
```html
<div class="jsx-parser">
  <div><ReactComponent /></div>
</div>
```

In order to get your component to bind, you'll need:
```javascript
import ReactComponent from './path/to/your/component'

render = () => (
  <JsxParser 
    bindings={{ ReactComponent }} /* << this is necessary for JsxParser to render your component */
    jsx="<script></script><div><ReactComponent /></div>"
  />
)

```

**Comment by TroyAlford** [comment] 2018-02-17 03:56
I'm closing this because I can't reproduce your issue, @vatsalvora. Please feel free to re-open if my suggestions, above, don't resolve!

**Closed by TroyAlford** 2018-02-17 03:56 UTC
