### ISSUE TITLE
Problems with arrays

### ISSUE THREAD

**Issue by ashleyjsands** [TroyAlford/react-jsx-parser#70] opened 2018-10-03 01:17 UTC
It appears I can't use arrays with this package. When I have the following code:
```
<JsxParser
	bindings={{
		Test: ["a", "b", "c"]
	}}
	components={{ Navigation }}
	jsx={`
		<div>
			{Test[0]}
			{Test.map(x => <p>{x}</p>)}
		</div>
	`}
/>
```
Nothing is rendered in the div. The map code causes a warning to occur:
> Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

So I may have gotten the syntax wrong, or it may be because this package doesn't explicitly support incline functions. Either way, is there a way to use arrays with this package so I can output JSX for each element in an array?

**Comment by TroyAlford** [comment] 2018-10-04 15:36
In general, what you're going to want to do in this case is create a component, then pass in its bindings, rather than essentially creating inline components as you're doing above.

Here's a fairly minimalistic example to consider. :)

```javascript
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import JsxParser from 'react-jsx-parser';

const Menu = ({ items }) => (
  <ul>
    {items.map((item, index) => (
      <li key={index}>{item}</li>
    ))}
  </ul>
)

ReactDOM.render(
  <JsxParser
    bindings={{ 
      menuItems1: ['a', 'b', 'c'],
      menuItems2: [1, 2, 3]
    }}
    components={{ Menu }}
    jsx={`
      <Menu items={menuItems1} />
      <Menu items={menuItems2} />
    `}
  />
, document.getElementById('root'));
```

**Comment by TroyAlford** [comment] 2018-10-04 15:38
That said, the ability to index into an Array bound as a prop is probably something we should support. I'm not sure when I can get to that at the moment, but I've marked this as an open `enhancement` request. PRs are also very welcome. :)

**Comment by ashleyjsands** [comment] 2018-10-08 02:27
@TroyAlford thanks for your help. That has solved my problem but I don't understand why I can't have an inline component because essentially the Menu component now contains those inline components instead.

**Comment by TroyAlford** [comment] 2018-10-16 22:14
Yes, I can totally understand why this might feel confusing.

The issue is that at the moment, I don't think the parser handles Array syntax. As a result, it simply can't parse the `[]` when you put it inline. This is something I'd like to add in the future - I'm just not sure when I'll have the time.

I'm open to a PR if you'd like to add it to the syntax processor?

**Closed** 2018-11-09 23:42 UTC
Labels: enhancement, question
