### ISSUE TITLE
Issues with using the attribute “maxLength”

### ISSUE THREAD

**Issue by MichaelMoVaPr** [TroyAlford/react-jsx-parser#225] opened 2022-03-11 09:10 UTC
When I use the maxLength attribute in my custom component, reactjsxparser will force maxLength to maxlength. How to mask this conversion，the code is just like this
`<JsxParser jsx={‘<component maxLength={0}/>’} components={{ ...components }} blacklistedAttrs={[]} />`
and I receive the attrbute in `<component>` is "maxlength"，how can I receive the "maxLength"

**Comment by TroyAlford** [comment] 2022-03-12 19:31
This should work fine. I can't tell what's wrong with your code without an actual example of how you're doing this. Here's a code sandbox showing that what you're trying to do works: https://codesandbox.io/s/jsx-parser-issues-4pkuh?file=/src/App.js

My best guess is that you aren't properly registering `component`. When you do `components={{ ...components }}` I can't tell what your `components` variable is in order to evaluate how the `...` spread operator is going to work.

If your `components` is an array, for instance - this won't work at all. If your `components` variable is an object of `name: Component` pairs, it should work - but in that case, you should just be doing `components={components}`.

I'm going to close this for now, since I can't repro. If you want me to take a look again, please provide a code sandbox with a working reproduction of what's broken.

**Closed as completed by TroyAlford** 2022-03-12 19:31 UTC
Labels: question, can't reproduce

**Comment by MichaelMoVaPr** [comment] 2022-03-14 03:51
I'm sorry I provided a wrong description
[https://codesandbox.io/embed/jsx-parser-issues-forked-irufym?fontsize=14&hidenavigation=1&theme=dark](url)
look at these code, I use the props maxlength in the Component1, but the maxlength is undefined in the Component1, and the maxLength is defined, and I just want to receive the maxlength rather than maxLength

**Comment by TroyAlford** [comment] 2022-03-15 20:34
I believe the issue here is that you're using a recognized prop (`maxLength`) which is a valid intrinsic on `input[type="text"]`. My suspicion is that React is handling that in a special way, for interoperability with HTML5 elements which use it. As a result, it treats `maxlength` and `maxLength` as interchangeable (because a DOM node's `attributes` are case-insensitive).

Here's an example to refer to:
https://codesandbox.io/s/jsx-parser-issues-forked-k29gvu?file=/src/App.js

As you can see from the above, non-reserved props are treated properly. `foo` and `Foo` are treated as independent from one another, and parsed correctly into 2 separate props. `maxlength` and `maxLength`, however, are treated as identical, and the `camelCase` version is the one that's actually bound.

All of that said - the fact that `maxLength` is working seems more _correct_ to me than if `maxlength` was working. The fact that React auto-corrects this into `camelCase` is consistent with the general styleguide that people use with React apps, and does not seem problematic to me.

If you need to meaningfully distinguish, here, my suggestion is to use a non-reserved prop name like `maximumLength`.
